-- Analytics foundation for /search featured sidebar:
-- 1) Persist view events
-- 2) Keep increment RPCs writing events
-- 3) Expose temporal aggregates (24h / 7d / 30d)

create table if not exists public.company_view_events (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  viewed_at timestamptz not null default timezone('utc', now())
);

create index if not exists company_view_events_company_id_idx
  on public.company_view_events(company_id);

create index if not exists company_view_events_viewed_at_idx
  on public.company_view_events(viewed_at desc);

create index if not exists company_view_events_company_viewed_idx
  on public.company_view_events(company_id, viewed_at desc);

alter table public.company_view_events enable row level security;

drop function if exists public.increment_view(text);

create or replace function public.increment_view(company_slug text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_count integer;
  target_company_id uuid;
begin
  update public.companies
  set views_count = coalesce(views_count, 0) + 1
  where slug = company_slug
  returning id, views_count into target_company_id, updated_count;

  if target_company_id is not null then
    insert into public.company_view_events (company_id)
    values (target_company_id);
  end if;

  return coalesce(updated_count, 0);
end;
$$;

drop function if exists public.increment_views(uuid);

create or replace function public.increment_views(company_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_count integer;
begin
  update public.companies
  set views_count = coalesce(views_count, 0) + 1
  where id = company_id
  returning views_count into updated_count;

  if found then
    insert into public.company_view_events (company_id)
    values (company_id);
  end if;

  return coalesce(updated_count, 0);
end;
$$;

grant execute on function public.increment_view(text) to anon;
grant execute on function public.increment_view(text) to authenticated;
grant execute on function public.increment_views(uuid) to anon;
grant execute on function public.increment_views(uuid) to authenticated;

drop function if exists public.get_featured_companies_analytics();

create or replace function public.get_featured_companies_analytics()
returns table (
  slot text,
  company_id uuid,
  company_name text,
  city text,
  sector text,
  slug text,
  views_24h bigint,
  bravos_7d bigint,
  views_30d bigint,
  bravos_30d bigint
)
language sql
security definer
set search_path = public
as $$
with views_24 as (
  select
    cve.company_id,
    count(*)::bigint as views_24h
  from public.company_view_events cve
  where cve.viewed_at >= timezone('utc', now()) - interval '24 hours'
  group by cve.company_id
),
bravos_7 as (
  select
    cv.company_id,
    count(*)::bigint as bravos_7d
  from public.company_votes cv
  where cv.created_at >= timezone('utc', now()) - interval '7 days'
  group by cv.company_id
),
views_30 as (
  select
    cve.company_id,
    count(*)::bigint as views_30d
  from public.company_view_events cve
  where cve.viewed_at >= timezone('utc', now()) - interval '30 days'
  group by cve.company_id
),
bravos_30 as (
  select
    cv.company_id,
    count(*)::bigint as bravos_30d
  from public.company_votes cv
  where cv.created_at >= timezone('utc', now()) - interval '30 days'
  group by cv.company_id
),
company_stats as (
  select
    c.id as company_id,
    c.name as company_name,
    c.city,
    c.sector,
    c.slug,
    coalesce(v24.views_24h, 0) as views_24h,
    coalesce(b7.bravos_7d, 0) as bravos_7d,
    coalesce(v30.views_30d, 0) as views_30d,
    coalesce(b30.bravos_30d, 0) as bravos_30d,
    coalesce(c.views_count, 0) as total_views,
    coalesce(c.bigup, 0) as total_bravos,
    (coalesce(v30.views_30d, 0) + (coalesce(b30.bravos_30d, 0) * 20))::numeric as combo_score
  from public.companies c
  left join views_24 v24 on v24.company_id = c.id
  left join bravos_7 b7 on b7.company_id = c.id
  left join views_30 v30 on v30.company_id = c.id
  left join bravos_30 b30 on b30.company_id = c.id
  where nullif(trim(c.slug), '') is not null
),
company_of_day as (
  select *
  from company_stats
  order by views_24h desc, total_views desc
  limit 1
),
champion_of_week as (
  select *
  from company_stats
  order by bravos_7d desc, total_bravos desc
  limit 1
),
pme_of_month as (
  select *
  from company_stats
  order by combo_score desc, total_views desc
  limit 1
)
select
  'company_of_day'::text as slot,
  cod.company_id,
  cod.company_name,
  cod.city,
  cod.sector,
  cod.slug,
  cod.views_24h,
  cod.bravos_7d,
  cod.views_30d,
  cod.bravos_30d
from company_of_day cod

union all

select
  'champion_of_week'::text as slot,
  cow.company_id,
  cow.company_name,
  cow.city,
  cow.sector,
  cow.slug,
  cow.views_24h,
  cow.bravos_7d,
  cow.views_30d,
  cow.bravos_30d
from champion_of_week cow

union all

select
  'pme_of_month'::text as slot,
  pom.company_id,
  pom.company_name,
  pom.city,
  pom.sector,
  pom.slug,
  pom.views_24h,
  pom.bravos_7d,
  pom.views_30d,
  pom.bravos_30d
from pme_of_month pom;
$$;

grant execute on function public.get_featured_companies_analytics() to anon;
grant execute on function public.get_featured_companies_analytics() to authenticated;
