-- Store one BigUp vote per authenticated user and company.
-- This table lets us prevent duplicate votes while keeping the aggregate counter on companies.

create table if not exists public.company_votes (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  constraint company_votes_company_user_key unique (company_id, user_id)
);

create index if not exists company_votes_company_id_idx on public.company_votes(company_id);
create index if not exists company_votes_user_id_idx on public.company_votes(user_id);

alter table public.company_votes enable row level security;

create policy "Users can read their own company votes"
on public.company_votes
for select
to authenticated
using (auth.uid() = user_id);

grant select on public.company_votes to authenticated;

alter table public.companies
add column if not exists bigup integer not null default 0;

drop function if exists public.increment_bigup(uuid);

create or replace function public.increment_bigup(p_company_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid;
  inserted_vote_id bigint;
  updated_count integer;
begin
  current_user_id := auth.uid();

  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  insert into public.company_votes (company_id, user_id)
  values (p_company_id, current_user_id)
  on conflict (company_id, user_id) do nothing
  returning id into inserted_vote_id;

  if inserted_vote_id is not null then
    update public.companies c
    set bigup = coalesce(c.bigup, 0) + 1
    where c.id = p_company_id
    returning c.bigup into updated_count;

    return jsonb_build_object(
      'bigup', coalesce(updated_count, 0),
      'voted', true,
      'created_vote', true
    );
  end if;

  select coalesce(c.bigup, 0)
  into updated_count
  from public.companies c
  where c.id = p_company_id;

  return jsonb_build_object(
    'bigup', coalesce(updated_count, 0),
    'voted', true,
    'created_vote', false
  );
end;
$$;

grant execute on function public.increment_bigup(uuid) to authenticated;
